


# artists 




Team : {
              modelling  : [],

              rigging : [],

              animation : [LOURO],

              lighting : [],

              fx : [],

              comp : [],


        }