# Launch config


# This config forces the start_cmd_dev / production.py to use a specific version of the pipeline build, 
# IF the variable is left blank "", then the start tool will automatically use the latest version, if the variable is specific, then 
# the start will use the specific version of the pipeline build
# v1.0.0 or ""

development_build : "" # This might be broken, need to re-check it sometime.
production_build : ""

Pipeline_name: 'PIPEDREAMS'
Pipeline_Path: "D:\\work\\projects\\3D\\projects"

user_name: "louis"

maya_version: 2022
houdini_version: 19.0.383

# UI Start
only_PipeDreams_Projects: True # Only list projects created with PipeDreams.

logger_disabled: False # Enable or Disable the loggers. False = the logger is Active.

allow_user_preferences: True