# Pipeline config

Pipeline_name: 'Pipedreams'
#Pipeline_root: "C:\\custom_program_files\\pipeline\\PipeDreams"
Pipeline_Path: "D:\\work\\projects\\3D\\projects"
path_to_extra_environments: "D:\\work\\projects\\dev\\projects\\PIPEDREAMS\\pipedreams\\admin\\data\\environments\\maya\\important_env.txt"
#home_dir: "C:\\Users\\louro\\Documents\\projects"

user_name: "louis"

maya_version: 2022
houdini_version: 19.0.383

create_overlay: True
overlay_position: "bottom_left"
overlay_size: "800"
overlay_image_dir: "C:\\custom_program_files\\PipeDreams\\PipeDreams\\cmd_line\\resources\\logo"
image_to_overlay: "logo_name.png"